-- SE2222 - Database Systems - Week 02 Lab (October 1, 2021)
-- Some of the data prepared help of the website https://www.randomlists.com/. (Last access: September 28, 2021)

DROP DATABASE IF EXISTS week02_lab;
CREATE DATABASE week02_lab;
USE week02_lab;

CREATE TABLE student(
student_number NUMERIC(4) NOT NULL,
name           VARCHAR(32),
surname        VARCHAR(32),
department     VARCHAR(64),
gpa            FLOAT);

INSERT INTO student VALUES(1127, "Dawn", "Trevino", "Computer Engineering", 3.31);
INSERT INTO student VALUES(9749, "Tyson", "Mcdaniel", "Industrial Engineering", 3.3);
INSERT INTO student VALUES(5581, "Raven", "Barker", "Civil Engineering", 3.69);
INSERT INTO student VALUES(7501, "Edward", "Zhang", "Film Design", 2.19);
INSERT INTO student VALUES(4618, "Love", "Flynn", "Biology", 1.95);
INSERT INTO student VALUES(5266, "Varian", "Howe", "Astronomy", 3.46);
INSERT INTO student VALUES(8268, "Verena", "Black", "Electrical and Electronics Engineering", 2.17);
INSERT INTO student VALUES(7949, "Gabriel", "Montgomery", "Astronomy", 3.4);
INSERT INTO student VALUES(6630, "Tristan", "Holt", "Industrial Design", 2.89);
INSERT INTO student VALUES(2280, "Ocean", "Waters", "Business Administration", 2.05);
INSERT INTO student VALUES(6356, "Dean", "Faulkner", "Computer Engineering", 1.99);
INSERT INTO student VALUES(5296, "Arden", "Mora", "Graphic Design", 3.73);
INSERT INTO student VALUES(8341, "Kate", "Marshall", "Software Engineering", 2.81);
INSERT INTO student VALUES(6556, "Taye", "Lyons", "Physics", 2.14);
INSERT INTO student VALUES(9058, "Quintin", "Higgins", "Industrial Design", 3.89);
INSERT INTO student VALUES(8689, "Jeremy", "Huerta", "Chemistry", 3.56);
INSERT INTO student VALUES(1373, "Drake", "Armstrong", "Civil Engineering", 3.75);
INSERT INTO student VALUES(5414, "Kingston", "Lindsey", "Software Engineering", 3.31);
INSERT INTO student VALUES(8136, "Hope", "Meadows", "Film Design", 1.78);
INSERT INTO student VALUES(4380, "Brandt", "Conrad", "International Trade and Finance", 3.51);
INSERT INTO student VALUES(5807, "Tanner", "Thornton", "Biology", 3.48);
INSERT INTO student VALUES(9307, "Wade", "Werner", "Physics", 2.95);
INSERT INTO student VALUES(5619, "William", "Lyons", "Graphic Design", 3.83);
INSERT INTO student VALUES(6101, "Jax", "Golden", "Chemistry", 2.76);
INSERT INTO student VALUES(8158, "Bailey", "Reilly", "Biology", 3.86);
INSERT INTO student VALUES(6050, "Paul", "Norris", "Music", 2.21);
INSERT INTO student VALUES(4489, "Kae", "Chung", "Logistics Management", 2.98);
INSERT INTO student VALUES(4739, "Janetta", "Knight", "Civil Engineering", 3.78);
INSERT INTO student VALUES(3295, "Leonie", "Villarreal", "Astronomy", 3.3);
INSERT INTO student VALUES(7522, "Lane", "Knox", "Chemistry", 2.33);
INSERT INTO student VALUES(4575, "Garrison", "Norman", "Logistics Management", 3.23);
INSERT INTO student VALUES(4434, "Caylen", "Petty", "Software Engineering", 2.97);
INSERT INTO student VALUES(9467, "Nevin", "Mercer", "Biology", 2.25);
INSERT INTO student VALUES(3514, "Syllable", "Chavez", "Civil Engineering", 2.01);
INSERT INTO student VALUES(3441, "Wade", "Mercer", "Industrial Engineering", 2.72);
INSERT INTO student VALUES(5091, "Jacklyn", "Santiago", "Electrical and Electronics Engineering", 2.05);
INSERT INTO student VALUES(4539, "Vernon", "Mays", "International Trade and Finance", 3.52);
INSERT INTO student VALUES(3824, "Anthony", "Banks", "Music", 1.96);
INSERT INTO student VALUES(3846, "Cerise", "Watkins", "Biology", 2.21);
INSERT INTO student VALUES(2328, "Ocean", "Weber", "Music", 3.87);
INSERT INTO student VALUES(5346, "Ricardo", "Jacobson", "Software Engineering", 1.96);
INSERT INTO student VALUES(3685, "Fawn", "Butler", "Mechanical Engineering", 3.28);
INSERT INTO student VALUES(6891, "Lydon", "Shepherd", "Mathematics", 3.74);
INSERT INTO student VALUES(4011, "Louis", "Hendricks", "Physics", 1.96);
INSERT INTO student VALUES(8643, "Cash", "Mcfarland", "Architecture", 2.28);
INSERT INTO student VALUES(2516, "Benjamin", "Conley", "Biology", 3.85);
INSERT INTO student VALUES(2405, "Hyrum", "Dean", "Business Administration", 2.58);
INSERT INTO student VALUES(1486, "Fernando", "Rice", "Software Engineering", 2.25);
INSERT INTO student VALUES(5052, "Ryder", "Wilcox", "Chemistry", 2.66);
INSERT INTO student VALUES(6069, "Judd", "Lane", "Electrical and Electronics Engineering", 3.06);
INSERT INTO student VALUES(1976, "Neil", "Padilla", "Business Administration", 3.18);
INSERT INTO student VALUES(2707, "Carlen", "Hampton", "Civil Engineering", 2.0);
INSERT INTO student VALUES(7434, "Sophia", "Grant", "Animation", 3.25);
INSERT INTO student VALUES(9044, "Joan", "Mercado", "Chemistry", 3.6);
INSERT INTO student VALUES(2357, "Luke", "Jefferson", "Civil Engineering", 1.86);
INSERT INTO student VALUES(1777, "Julian", "Holloway", "Biology", 2.74);
INSERT INTO student VALUES(1504, "Kae", "Pierce", "Software Engineering", 2.14);
INSERT INTO student VALUES(8419, "Xavier", "Walls", "Animation", 3.65);
INSERT INTO student VALUES(4300, "Doran", "Lutz", "Physics", 3.48);
INSERT INTO student VALUES(6970, "Sophia", "Sanders", "Industrial Engineering", 2.71);
INSERT INTO student VALUES(8249, "Juan", "Williamson", "Chemistry", 2.83);
INSERT INTO student VALUES(9334, "Damien", "Gill", "Logistics Management", 3.94);
INSERT INTO student VALUES(1294, "Ashten", "Sosa", "Computer Engineering", 3.9);
INSERT INTO student VALUES(6679, "Edward", "Thomas", "Physics", 3.21);
INSERT INTO student VALUES(7076, "Kaitlin", "Aguilar", "Animation", 2.31);
INSERT INTO student VALUES(6154, "Debree", "Shaw", "Music", 1.91);
INSERT INTO student VALUES(2519, "Ray", "Bullock", "Music", 2.04);
INSERT INTO student VALUES(4448, "Gillian", "Jordan", "Architecture", 3.83);
INSERT INTO student VALUES(8911, "Eloise", "Hubbard", "Software Engineering", 2.67);
INSERT INTO student VALUES(8116, "Glenn", "Patel", "Graphic Design", 3.98);
INSERT INTO student VALUES(4409, "Murphy", "Marsh", "Software Engineering", 2.72);
INSERT INTO student VALUES(9870, "Mirabel", "Holt", "Software Engineering", 2.62);
INSERT INTO student VALUES(9838, "Judd", "Pace", "Economics", 1.84);
INSERT INTO student VALUES(3624, "Justin", "Bolton", "International Trade and Finance", 2.47);
INSERT INTO student VALUES(4587, "Doran", "Dyer", "Physics", 2.29);
INSERT INTO student VALUES(2733, "Paul", "Andrade", "Electrical and Electronics Engineering", 1.81);
INSERT INTO student VALUES(2223, "Trey", "Hensley", "Biology", 2.16);
INSERT INTO student VALUES(3712, "Payten", "Dunn", "Mathematics", 3.49);
INSERT INTO student VALUES(3747, "Miriam", "Gomez", "Logistics Management", 2.14);
INSERT INTO student VALUES(5544, "Hope", "Bonilla", "Biology", 2.89);
INSERT INTO student VALUES(8823, "Aryn", "Dunn", "Animation", 3.61);
INSERT INTO student VALUES(7018, "Taylore", "Travis", "Business Administration", 3.86);
INSERT INTO student VALUES(4354, "Felix", "Patton", "Energy Systems Engineering", 2.37);
INSERT INTO student VALUES(5540, "Silvia", "Kim", "Film Design", 3.18);
INSERT INTO student VALUES(3056, "Sophia", "Snyder", "Animation", 3.05);
INSERT INTO student VALUES(9972, "Harriet", "Cline", "International Trade and Finance", 2.72);
INSERT INTO student VALUES(2043, "Hyrum", "Farmer", "Industrial Engineering", 2.84);
INSERT INTO student VALUES(1614, "Bree", "Hill", "Biology", 3.39);
INSERT INTO student VALUES(7011, "Matilda", "Huang", "Astronomy", 3.2);
INSERT INTO student VALUES(1738, "Tavian", "Hancock", "Biology", 3.81);
INSERT INTO student VALUES(7138, "Rose", "Knox", "Architecture", 2.09);
INSERT INTO student VALUES(4994, "Jae", "Bradshaw", "Architecture", 3.46);
INSERT INTO student VALUES(6296, "Syllable", "Chandler", "Industrial Design", 2.73);
INSERT INTO student VALUES(1298, "Luke", "Hayden", "Electrical and Electronics Engineering", 2.14);
INSERT INTO student VALUES(8950, "Elias", "Kline", "Music", 3.25);
INSERT INTO student VALUES(1869, "Zion", "Mclean", "Film Design", 2.98);
INSERT INTO student VALUES(5866, "Rebecca", "Brennan", "Logistics Management", 3.74);
INSERT INTO student VALUES(6095, "Bernice", "Bennett", "Software Engineering", 3.55);
INSERT INTO student VALUES(5336, "Caleb", "Fitzgerald", "Mechanical Engineering", 1.99);
INSERT INTO student VALUES(6285, "Avery", "Rice", "Electrical and Electronics Engineering", 2.24);
INSERT INTO student VALUES(9824, "Allison", "Vaughn", "Computer Engineering", 3.38);
INSERT INTO student VALUES(8746, "Carelyn", "Simpson", "Film Design", 4.0);
INSERT INTO student VALUES(5332, "Bailey", "May", "Animation", 2.62);
INSERT INTO student VALUES(2272, "Jeremy", "Velez", "Energy Systems Engineering", 2.7);
INSERT INTO student VALUES(6366, "Leo", "Potter", "Energy Systems Engineering", 2.49);
INSERT INTO student VALUES(8616, "Carleen", "Bonilla", "Physics", 2.14);
INSERT INTO student VALUES(1324, "Nevin", "Willis", "Biology", 3.51);
INSERT INTO student VALUES(5605, "Elias", "Hunter", "Computer Engineering", 3.91);
INSERT INTO student VALUES(4260, "Anthony", "Espinoza", "Physics", 3.11);
INSERT INTO student VALUES(2626, "Dash", "Huber", "International Trade and Finance", 1.8);
INSERT INTO student VALUES(5690, "Joanna", "Whitehead", "Film Design", 2.15);
INSERT INTO student VALUES(7051, "Rory", "Carr", "Software Engineering", 2.9);
INSERT INTO student VALUES(6035, "Judd", "Leblanc", "Civil Engineering", 2.89);
INSERT INTO student VALUES(9051, "Lynn", "Weiss", "Industrial Engineering", 3.54);
INSERT INTO student VALUES(6819, "Amity", "Johnston", "Industrial Engineering", 3.5);
INSERT INTO student VALUES(2126, "Naveen", "Fitzpatrick", "Physics", 2.58);
INSERT INTO student VALUES(8211, "Gavin", "Hudson", "Business Administration", 2.33);
INSERT INTO student VALUES(9429, "Felix", "Ho", "Biology", 3.74);
INSERT INTO student VALUES(2663, "Aaron", "Knight", "Logistics Management", 3.66);
INSERT INTO student VALUES(4836, "Ashten", "Ramos", "Animation", 2.42);
INSERT INTO student VALUES(8489, "Gregory", "Alvarez", "Architecture", 2.94);
INSERT INTO student VALUES(1189, "Marcella", "Tapia", "Economics", 2.31);
INSERT INTO student VALUES(1301, "Zane", "Key", "Animation", 3.93);
INSERT INTO student VALUES(7830, "Varian", "Nichols", "Chemistry", 3.14);
INSERT INTO student VALUES(5397, "Apollo", "Stevenson", "Film Design", 3.09);
INSERT INTO student VALUES(6432, "Coralie", "Delacruz", "Business Administration", 2.77);
INSERT INTO student VALUES(7191, "Cameron", "Mcgrath", "Energy Systems Engineering", 1.83);
INSERT INTO student VALUES(8127, "Miranda", "Love", "Chemistry", 3.54);
INSERT INTO student VALUES(8297, "Beck", "Hardin", "Film Design", 1.95);
INSERT INTO student VALUES(6290, "Sue", "Villarreal", "Computer Engineering", 3.13);
INSERT INTO student VALUES(1684, "Viola", "Rodriguez", "Economics", 2.11);
INSERT INTO student VALUES(5831, "Mae", "Santiago", "Industrial Design", 3.13);
INSERT INTO student VALUES(8822, "Beck", "Li", "Animation", 3.97);
INSERT INTO student VALUES(3018, "Dean", "Henderson", "Industrial Engineering", 2.44);
INSERT INTO student VALUES(5300, "Verena", "Stark", "Energy Systems Engineering", 2.07);
INSERT INTO student VALUES(8401, "Vernon", "Rowe", "Logistics Management", 2.75);
INSERT INTO student VALUES(4741, "Lucinda", "Rhodes", "Electrical and Electronics Engineering", 3.13);
INSERT INTO student VALUES(2064, "Sutton", "Conley", "Film Design", 2.61);
INSERT INTO student VALUES(9227, "Lynn", "Leach", "Industrial Engineering", 3.28);
INSERT INTO student VALUES(7374, "Debree", "Young", "International Trade and Finance", 2.24);
INSERT INTO student VALUES(2875, "Sullivan", "Mullen", "International Trade and Finance", 1.87);
INSERT INTO student VALUES(9491, "Cameron", "Kim", "Mechanical Engineering", 2.12);
INSERT INTO student VALUES(8001, "Arthur", "Warren", "Music", 1.76);
INSERT INTO student VALUES(6631, "Cody", "Stanley", "Computer Engineering", 3.42);
INSERT INTO student VALUES(6500, "Silvia", "Fry", "Chemistry", 3.26);
INSERT INTO student VALUES(6081, "Trey", "Barry", "Computer Engineering", 3.81);
INSERT INTO student VALUES(9914, "Jolee", "Fitzgerald", "Electrical and Electronics Engineering", 2.36);
INSERT INTO student VALUES(2210, "Eli", "Copeland", "Astronomy", 3.37);
INSERT INTO student VALUES(2135, "Ricardo", "Dean", "Biology", 2.52);
INSERT INTO student VALUES(2216, "Blaise", "Morton", "Music", 3.84);
INSERT INTO student VALUES(6975, "Joseph", "Schaefer", "Music", 2.54);
INSERT INTO student VALUES(2120, "Evelyn", "Calderon", "Software Engineering", 3.28);
INSERT INTO student VALUES(5454, "Denver", "Mccormick", "Energy Systems Engineering", 3.67);
INSERT INTO student VALUES(9416, "Ellice", "Haley", "Mathematics", 3.16);
INSERT INTO student VALUES(2717, "Robin", "Conway", "International Trade and Finance", 3.31);
INSERT INTO student VALUES(8224, "Ace", "Hobbs", "Music", 1.97);
INSERT INTO student VALUES(3193, "Amelia", "Santos", "Economics", 3.27);
INSERT INTO student VALUES(2116, "Justin", "Bean", "Industrial Design", 2.87);
INSERT INTO student VALUES(4709, "Zion", "Zavala", "Economics", 3.84);
INSERT INTO student VALUES(1828, "Annabel", "Reynolds", "Biology", 3.01);
INSERT INTO student VALUES(5189, "Oren", "Wilkerson", "Industrial Engineering", 2.91);
INSERT INTO student VALUES(7410, "Francis", "Mcmahon", "Energy Systems Engineering", 3.18);
INSERT INTO student VALUES(3601, "Conrad", "Haas", "Astronomy", 3.32);
INSERT INTO student VALUES(8415, "Isaiah", "Olson", "Computer Engineering", 3.3);
INSERT INTO student VALUES(5673, "Harriet", "Washington", "Business Administration", 1.81);
INSERT INTO student VALUES(3419, "Fernando", "Giles", "Architecture", 2.77);
INSERT INTO student VALUES(2089, "Haiden", "Reid", "Business Administration", 3.69);
INSERT INTO student VALUES(7769, "Miriam", "Howard", "Physics", 2.39);
INSERT INTO student VALUES(7456, "Silvia", "Wilkinson", "Logistics Management", 2.53);
INSERT INTO student VALUES(4338, "Hollyn", "Mccormick", "Software Engineering", 2.67);
INSERT INTO student VALUES(3306, "Wade", "Roman", "International Trade and Finance", 3.02);
INSERT INTO student VALUES(7979, "Joseph", "Oneal", "Mechanical Engineering", 3.92);
INSERT INTO student VALUES(1395, "Rayleen", "Hudson", "Architecture", 3.28);
INSERT INTO student VALUES(5082, "Aiden", "Bradley", "Industrial Design", 2.61);
INSERT INTO student VALUES(6381, "Denver", "Everett", "Mechanical Engineering", 3.22);
INSERT INTO student VALUES(9521, "Aiden", "Bryant", "Software Engineering", 3.26);
INSERT INTO student VALUES(3911, "Jaidyn", "Montoya", "Economics", 2.77);
INSERT INTO student VALUES(4420, "Oscar", "Buck", "Civil Engineering", 3.56);
INSERT INTO student VALUES(6370, "Dante", "Alvarez", "Music", 1.84);
INSERT INTO student VALUES(6562, "Annora", "Fry", "Software Engineering", 2.45);
INSERT INTO student VALUES(4649, "Anthony", "Parker", "Physics", 3.05);
INSERT INTO student VALUES(1531, "Elodie", "Benson", "Industrial Design", 2.64);
INSERT INTO student VALUES(4963, "Madeleine", "Mcguire", "Animation", 2.17);
INSERT INTO student VALUES(5361, "Felix", "Buchanan", "Economics", 2.59);
INSERT INTO student VALUES(1509, "Avery", "Williamson", "Computer Engineering", 3.67);
INSERT INTO student VALUES(8015, "Lane", "Williamson", "Biology", 3.77);
INSERT INTO student VALUES(3763, "Paul", "Davidson", "Graphic Design", 2.12);
INSERT INTO student VALUES(1899, "Annabel", "York", "Logistics Management", 2.54);
INSERT INTO student VALUES(5271, "Julina", "Mullins", "Architecture", 1.88);
INSERT INTO student VALUES(8246, "Lee", "Ellis", "Logistics Management", 3.31);
INSERT INTO student VALUES(1333, "Olive", "Foley", "Graphic Design", 1.94);
INSERT INTO student VALUES(6510, "Blaise", "Gonzales", "Mathematics", 2.61);
INSERT INTO student VALUES(9576, "Clementine", "Nichols", "Mechanical Engineering", 2.37);
INSERT INTO student VALUES(4414, "Paul", "Schmitt", "International Trade and Finance", 3.02);
INSERT INTO student VALUES(7721, "Oliver", "Harrell", "Mechanical Engineering", 2.78);
INSERT INTO student VALUES(9787, "Harriet", "Garrison", "Software Engineering", 2.77);
INSERT INTO student VALUES(3141, "Blayne", "Downs", "Architecture", 2.82);
INSERT INTO student VALUES(7459, "Rory", "Wright", "Mathematics", 2.27);
INSERT INTO student VALUES(5161, "Coy", "Tate", "Industrial Engineering", 3.2);
INSERT INTO student VALUES(5237, "Nicolas", "Huff", "Mechanical Engineering", 2.02);
INSERT INTO student VALUES(9006, "Coreen", "Blake", "Music", 2.58);
INSERT INTO student VALUES(8836, "Mae", "Massey", "Chemistry", 2.34);
INSERT INTO student VALUES(5828, "Denise", "Stanton", "Industrial Engineering", 3.21);
INSERT INTO student VALUES(3312, "Mae", "Herring", "Software Engineering", 2.03);
INSERT INTO student VALUES(8029, "Debree", "Harris", "Economics", 1.92);
INSERT INTO student VALUES(8287, "Kingston", "David", "Electrical and Electronics Engineering", 3.6);
INSERT INTO student VALUES(4462, "Felix", "Davies", "Mechanical Engineering", 3.45);
INSERT INTO student VALUES(5132, "Rose", "Moon", "Architecture", 3.54);
INSERT INTO student VALUES(8980, "Will", "Fletcher", "Mechanical Engineering", 3.59);
INSERT INTO student VALUES(1408, "Cameron", "Kaiser", "Biology", 2.32);
INSERT INTO student VALUES(3462, "Kai", "Wolfe", "Graphic Design", 3.5);
INSERT INTO student VALUES(7735, "Trevor", "Rowe", "Business Administration", 1.97);
INSERT INTO student VALUES(2661, "Rhett", "Mcfarland", "Economics", 3.46);
INSERT INTO student VALUES(6274, "Jeremy", "Esparza", "Computer Engineering", 2.82);
INSERT INTO student VALUES(7460, "Cody", "Cruz", "International Trade and Finance", 3.31);
INSERT INTO student VALUES(8870, "Anise", "Suarez", "Industrial Engineering", 1.78);
INSERT INTO student VALUES(9251, "Debree", "Chan", "Music", 1.92);
INSERT INTO student VALUES(5836, "Oliver", "Richmond", "Software Engineering", 3.93);
INSERT INTO student VALUES(4814, "Cerise", "Bautista", "Business Administration", 3.38);
INSERT INTO student VALUES(1736, "Wade", "Sheppard", "Software Engineering", 3.58);
INSERT INTO student VALUES(1868, "Zoe", "Thompson", "Graphic Design", 3.69);
INSERT INTO student VALUES(9874, "Julian", "Chang", "Graphic Design", 3.53);
INSERT INTO student VALUES(8314, "Shane", "Griffith", "Computer Engineering", 3.39);
INSERT INTO student VALUES(8915, "Justin", "English", "Computer Engineering", 1.89);
INSERT INTO student VALUES(3704, "Dante", "Gallagher", "Computer Engineering", 2.59);
INSERT INTO student VALUES(2080, "Garrison", "Barton", "Industrial Engineering", 2.16);
INSERT INTO student VALUES(8376, "Julina", "Vincent", "Economics", 3.61);
INSERT INTO student VALUES(8483, "Breean", "Mcclain", "Architecture", 2.14);
INSERT INTO student VALUES(4430, "Jae", "Duncan", "Business Administration", 3.52);
INSERT INTO student VALUES(4787, "Byron", "Holden", "Biology", 2.31);
INSERT INTO student VALUES(4322, "Paul", "Munoz", "International Trade and Finance", 3.52);
INSERT INTO student VALUES(4890, "Abraham", "Cohen", "Animation", 1.79);
INSERT INTO student VALUES(9742, "Karilyn", "Bullock", "Software Engineering", 3.6);
INSERT INTO student VALUES(1187, "Verena", "Erickson", "Industrial Design", 3.95);
INSERT INTO student VALUES(8444, "Cerise", "Carter", "Electrical and Electronics Engineering", 3.57);
INSERT INTO student VALUES(3290, "Madeleine", "Salazar", "Software Engineering", 2.77);
INSERT INTO student VALUES(5891, "Rayleen", "Osborne", "Business Administration", 3.49);
INSERT INTO student VALUES(5263, "Carlen", "Rich", "Software Engineering", 2.08);
INSERT INTO student VALUES(1114, "Krystan", "Sherman", "Electrical and Electronics Engineering", 2.67);
INSERT INTO student VALUES(9158, "Bree", "Gill", "Civil Engineering", 3.66);
INSERT INTO student VALUES(9653, "Zion", "Banks", "International Trade and Finance", 3.02);
INSERT INTO student VALUES(4745, "Bree", "Collins", "Architecture", 2.33);
INSERT INTO student VALUES(4566, "Preston", "Hays", "Astronomy", 3.32);
INSERT INTO student VALUES(3699, "Elijah", "Blankenship", "Mechanical Engineering", 2.38);
INSERT INTO student VALUES(2440, "Jane", "Perry", "International Trade and Finance", 2.74);
INSERT INTO student VALUES(8574, "June", "Graham", "Electrical and Electronics Engineering", 3.86);
INSERT INTO student VALUES(1884, "Murphy", "Leach", "Mathematics", 2.08);
INSERT INTO student VALUES(2528, "Aaron", "Whitney", "Energy Systems Engineering", 1.81);
INSERT INTO student VALUES(7804, "Carleen", "Bruce", "Energy Systems Engineering", 3.77);
INSERT INTO student VALUES(4775, "Jared", "Silva", "Biology", 2.82);
INSERT INTO student VALUES(2303, "Amelia", "Cain", "Music", 3.6);
INSERT INTO student VALUES(8352, "Timothy", "Martin", "International Trade and Finance", 2.01);
INSERT INTO student VALUES(9403, "Payten", "Velazquez", "Physics", 3.01);
INSERT INTO student VALUES(8148, "Jasper", "Taylor", "Logistics Management", 2.19);
INSERT INTO student VALUES(2033, "Kingston", "Skinner", "International Trade and Finance", 2.47);
INSERT INTO student VALUES(6287, "Nadeen", "Mullins", "Industrial Design", 2.36);
INSERT INTO student VALUES(5319, "Hugh", "Odonnell", "Industrial Engineering", 2.3);
INSERT INTO student VALUES(3438, "Jeremy", "Roth", "Physics", 3.42);
INSERT INTO student VALUES(7532, "Henry", "Lam", "Animation", 3.75);
INSERT INTO student VALUES(7579, "Rene", "Russell", "Architecture", 3.16);
INSERT INTO student VALUES(3504, "Timothy", "Lamb", "Architecture", 3.67);
INSERT INTO student VALUES(4956, "Harriet", "Nunez", "Architecture", 3.37);
INSERT INTO student VALUES(6991, "Troy", "Villarreal", "Computer Engineering", 2.54);
INSERT INTO student VALUES(6883, "Jane", "Floyd", "Economics", 2.22);
INSERT INTO student VALUES(6076, "Gregory", "Mccoy", "Physics", 3.59);
INSERT INTO student VALUES(9155, "Sharon", "Atkinson", "Film Design", 2.51);
INSERT INTO student VALUES(3991, "Abraham", "Wong", "Mechanical Engineering", 2.01);
INSERT INTO student VALUES(6333, "Krystan", "Barker", "Chemistry", 3.87);
INSERT INTO student VALUES(8346, "Levi", "Mayo", "Chemistry", 3.43);
INSERT INTO student VALUES(1475, "Rosalind", "Kim", "Software Engineering", 2.8);
INSERT INTO student VALUES(7684, "Coy", "Banks", "Civil Engineering", 1.75);
INSERT INTO student VALUES(6115, "Brooke", "Woods", "Software Engineering", 1.84);
INSERT INTO student VALUES(4016, "Preston", "Nixon", "Industrial Design", 1.95);
INSERT INTO student VALUES(6067, "Dean", "Stein", "Chemistry", 1.87);
INSERT INTO student VALUES(1665, "Amity", "Rodgers", "Film Design", 2.01);
INSERT INTO student VALUES(6712, "Karilyn", "Mcbride", "Biology", 2.07);
INSERT INTO student VALUES(5081, "Lynn", "Cox", "Computer Engineering", 2.32);
INSERT INTO student VALUES(1117, "Reese", "Chaney", "Civil Engineering", 2.96);
INSERT INTO student VALUES(1860, "June", "Gill", "Industrial Design", 2.2);
INSERT INTO student VALUES(4807, "Noel", "Barnes", "Logistics Management", 3.28);
INSERT INTO student VALUES(2312, "Tavian", "Barrera", "Computer Engineering", 3.89);
INSERT INTO student VALUES(6824, "Bernice", "Nash", "Computer Engineering", 2.02);
INSERT INTO student VALUES(5282, "Krystan", "Larsen", "Biology", 2.26);
INSERT INTO student VALUES(5729, "Ellen", "Shields", "Computer Engineering", 2.51);
INSERT INTO student VALUES(1814, "Denise", "Colon", "Biology", 3.77);
INSERT INTO student VALUES(7762, "Madeleine", "Hinton", "Economics", 3.92);
INSERT INTO student VALUES(9029, "Robin", "Guerra", "Animation", 3.03);
INSERT INTO student VALUES(9420, "Lane", "Forbes", "Biology", 3.48);
INSERT INTO student VALUES(6413, "Varian", "Ballard", "Industrial Engineering", 3.93);
INSERT INTO student VALUES(3919, "Brendon", "Dixon", "Physics", 3.1);
INSERT INTO student VALUES(4644, "Riley", "Ponce", "Chemistry", 2.59);
INSERT INTO student VALUES(2847, "Ace", "Jimenez", "Civil Engineering", 3.44);
INSERT INTO student VALUES(9422, "George", "Marquez", "Civil Engineering", 2.65);
INSERT INTO student VALUES(1118, "Blaise", "Lara", "Electrical and Electronics Engineering", 3.78);
INSERT INTO student VALUES(8196, "Janetta", "Dillon", "Physics", 3.68);
INSERT INTO student VALUES(4742, "Matilda", "Norris", "Computer Engineering", 2.79);
INSERT INTO student VALUES(9621, "Monteen", "Pope", "Physics", 2.78);
INSERT INTO student VALUES(3310, "Carleen", "Shelton", "Software Engineering", 2.55);
INSERT INTO student VALUES(3537, "Jae", "Villa", "Industrial Engineering", 3.14);
INSERT INTO student VALUES(1599, "Ray", "Tyler", "Industrial Design", 3.43);
INSERT INTO student VALUES(6494, "Gregory", "Cervantes", "Civil Engineering", 3.6);
INSERT INTO student VALUES(6435, "Lawrence", "Maynard", "Animation", 2.7);
INSERT INTO student VALUES(7613, "Coy", "Lang", "Animation", 2.44);
INSERT INTO student VALUES(2503, "Bailee", "James", "Logistics Management", 3.48);
INSERT INTO student VALUES(8220, "Arthur", "Montoya", "Civil Engineering", 2.77);
INSERT INTO student VALUES(4581, "Payten", "Davenport", "Animation", 3.88);
INSERT INTO student VALUES(3296, "Debree", "Payne", "Astronomy", 3.04);
INSERT INTO student VALUES(2374, "Dominick", "Solomon", "Biology", 3.62);
INSERT INTO student VALUES(7612, "Love", "Lowery", "Logistics Management", 2.92);
INSERT INTO student VALUES(7827, "George", "Thornton", "Civil Engineering", 2.55);
INSERT INTO student VALUES(5722, "Janetta", "Stanton", "Industrial Design", 2.52);
INSERT INTO student VALUES(5375, "Meaghan", "Becker", "International Trade and Finance", 2.47);
INSERT INTO student VALUES(8829, "Aryn", "Lopez", "Biology", 2.09);
INSERT INTO student VALUES(2191, "Felix", "Mcgrath", "Energy Systems Engineering", 2.56);
INSERT INTO student VALUES(2128, "Anneliese", "Mays", "Architecture", 2.97);
INSERT INTO student VALUES(8743, "Hugh", "Camacho", "Film Design", 3.12);
INSERT INTO student VALUES(5860, "Hugh", "Santiago", "Animation", 2.9);
INSERT INTO student VALUES(8919, "Doran", "Barajas", "Architecture", 3.72);
INSERT INTO student VALUES(7865, "Brock", "Bray", "Economics", 3.39);
INSERT INTO student VALUES(1797, "Gregory", "Blevins", "Astronomy", 2.53);
INSERT INTO student VALUES(1134, "Jared", "Molina", "Mathematics", 2.97);
INSERT INTO student VALUES(3741, "Benjamin", "Dawson", "Logistics Management", 3.61);
INSERT INTO student VALUES(9063, "Dash", "Robertson", "Physics", 2.49);
INSERT INTO student VALUES(4664, "Abe", "Farley", "Business Administration", 3.32);
INSERT INTO student VALUES(6397, "Clementine", "Harrison", "Physics", 2.1);
INSERT INTO student VALUES(9264, "Bailee", "Anthony", "Biology", 1.76);
INSERT INTO student VALUES(2115, "Marcellus", "Robbins", "Architecture", 3.88);
INSERT INTO student VALUES(7589, "Claudia", "Fry", "Animation", 3.83);
INSERT INTO student VALUES(2880, "Devon", "Mendez", "Industrial Engineering", 3.05);
INSERT INTO student VALUES(6476, "Ellory", "Page", "Graphic Design", 2.05);
INSERT INTO student VALUES(6402, "Tyson", "Choi", "Animation", 3.78);
INSERT INTO student VALUES(1277, "Julian", "Jacobson", "Astronomy", 3.18);
INSERT INTO student VALUES(7284, "Olive", "Walter", "Film Design", 2.56);
INSERT INTO student VALUES(9901, "Bree", "Sanders", "Business Administration", 2.33);
INSERT INTO student VALUES(9775, "Alice", "Wang", "Civil Engineering", 3.51);
INSERT INTO student VALUES(8368, "Jaidyn", "Vega", "Energy Systems Engineering", 3.82);
INSERT INTO student VALUES(8888, "Lane", "Foley", "Chemistry", 3.67);
INSERT INTO student VALUES(9111, "Jude", "Simon", "Chemistry", 1.85);
INSERT INTO student VALUES(3776, "Evony", "Mata", "Logistics Management", 3.05);
INSERT INTO student VALUES(3885, "Natalie", "Lindsey", "International Trade and Finance", 2.03);
INSERT INTO student VALUES(8809, "Trevor", "Herman", "Film Design", 2.6);
INSERT INTO student VALUES(5432, "Kalan", "Roman", "Physics", 1.98);
INSERT INTO student VALUES(2074, "Jasper", "Holder", "Mechanical Engineering", 1.81);
INSERT INTO student VALUES(2360, "Sherleen", "Kim", "Astronomy", 2.79);
INSERT INTO student VALUES(5045, "Lillian", "Ritter", "Business Administration", 3.39);
INSERT INTO student VALUES(1485, "Miriam", "Mullen", "Civil Engineering", 2.6);
INSERT INTO student VALUES(4919, "Blayne", "Le", "Graphic Design", 3.09);
INSERT INTO student VALUES(9549, "Charles", "Dillon", "Industrial Design", 2.21);
INSERT INTO student VALUES(9816, "Coreen", "Salas", "Graphic Design", 3.08);
INSERT INTO student VALUES(9510, "Lashon", "Montes", "International Trade and Finance", 3.92);
INSERT INTO student VALUES(7498, "Matilda", "Fitzgerald", "International Trade and Finance", 2.49);
INSERT INTO student VALUES(5546, "Blanche", "Fuentes", "Astronomy", 2.03);
INSERT INTO student VALUES(5609, "Reeve", "Haney", "Biology", 3.48);
INSERT INTO student VALUES(9266, "Charles", "Mclaughlin", "Industrial Engineering", 3.07);
INSERT INTO student VALUES(9142, "Vivian", "Chung", "Business Administration", 1.82);
INSERT INTO student VALUES(8922, "Reagan", "Vance", "Mechanical Engineering", 3.18);
INSERT INTO student VALUES(7621, "Trey", "Buck", "International Trade and Finance", 2.22);
INSERT INTO student VALUES(4280, "Porter", "Petersen", "Software Engineering", 2.13);
INSERT INTO student VALUES(1693, "Sherleen", "Dalton", "Industrial Design", 3.39);
INSERT INTO student VALUES(7409, "Evelyn", "Stokes", "Business Administration", 2.8);
INSERT INTO student VALUES(4953, "Lawrence", "Mullins", "Chemistry", 3.14);
INSERT INTO student VALUES(3435, "Susannah", "Sellers", "International Trade and Finance", 3.59);
INSERT INTO student VALUES(9081, "Byron", "Miranda", "Industrial Design", 3.39);
INSERT INTO student VALUES(5368, "Janetta", "Ellison", "Business Administration", 2.85);
INSERT INTO student VALUES(1161, "Riley", "Lynn", "Biology", 1.99);
INSERT INTO student VALUES(3983, "Annabel", "Haney", "Electrical and Electronics Engineering", 2.44);
INSERT INTO student VALUES(7967, "Rene", "Mcneil", "Business Administration", 2.93);
INSERT INTO student VALUES(9783, "Louis", "Lucero", "Industrial Design", 2.26);
INSERT INTO student VALUES(5822, "Marguerite", "Dillon", "Astronomy", 1.79);
INSERT INTO student VALUES(8277, "Silvia", "Montoya", "Civil Engineering", 2.87);
INSERT INTO student VALUES(7467, "Sharon", "Nguyen", "International Trade and Finance", 3.58);
INSERT INTO student VALUES(9153, "Krystan", "Webb", "Energy Systems Engineering", 3.44);
INSERT INTO student VALUES(4181, "Rory", "Miranda", "Chemistry", 3.02);
INSERT INTO student VALUES(1547, "Candice", "Mccarty", "Biology", 3.91);
INSERT INTO student VALUES(1677, "Dean", "Blackburn", "Industrial Design", 3.11);
INSERT INTO student VALUES(4344, "Rory", "Daugherty", "Logistics Management", 1.85);
INSERT INTO student VALUES(2393, "Natalie", "Li", "International Trade and Finance", 3.23);
INSERT INTO student VALUES(1993, "Cameron", "Hodge", "Industrial Design", 3.18);
INSERT INTO student VALUES(3916, "Everett", "Holland", "Architecture", 2.48);
INSERT INTO student VALUES(8665, "Bailey", "Singleton", "Industrial Design", 3.32);
INSERT INTO student VALUES(9788, "Joanna", "Harrison", "Architecture", 3.95);
INSERT INTO student VALUES(2864, "Michael", "Cooley", "Software Engineering", 3.95);
INSERT INTO student VALUES(9135, "Susannah", "Parker", "Software Engineering", 3.99);
INSERT INTO student VALUES(7298, "Sophia", "Mccarthy", "Software Engineering", 3.07);
INSERT INTO student VALUES(9880, "Elein", "Caldwell", "Computer Engineering", 3.46);
INSERT INTO student VALUES(7922, "Josiah", "Campos", "Electrical and Electronics Engineering", 2.87);
INSERT INTO student VALUES(3209, "Silvia", "Weeks", "Astronomy", 3.43);
INSERT INTO student VALUES(5031, "Jae", "Mooney", "Industrial Engineering", 1.95);
INSERT INTO student VALUES(6516, "Zion", "Giles", "Software Engineering", 2.98);
INSERT INTO student VALUES(4400, "Eli", "Goodwin", "Computer Engineering", 3.94);
INSERT INTO student VALUES(3153, "Ashten", "Mcgee", "Industrial Engineering", 3.93);
INSERT INTO student VALUES(5551, "Tobias", "Strickland", "Civil Engineering", 2.93);
INSERT INTO student VALUES(9984, "Malachi", "Brennan", "Software Engineering", 1.85);
INSERT INTO student VALUES(7330, "Joan", "Cruz", "Music", 2.28);
INSERT INTO student VALUES(4018, "Fern", "Hutchinson", "Physics", 1.88);
INSERT INTO student VALUES(5547, "Jared", "Bonilla", "Industrial Engineering", 3.02);
INSERT INTO student VALUES(5089, "Carleen", "Hill", "Physics", 2.59);
INSERT INTO student VALUES(1265, "Jackson", "Craig", "Animation", 3.38);
INSERT INTO student VALUES(9138, "Quintin", "Dalton", "Electrical and Electronics Engineering", 3.5);
INSERT INTO student VALUES(5425, "Daniel", "Huang", "Mechanical Engineering", 2.24);
INSERT INTO student VALUES(4240, "Zoe", "Randall", "Graphic Design", 1.85);
INSERT INTO student VALUES(2421, "Dawn", "Le", "Animation", 3.14);
INSERT INTO student VALUES(6040, "Fern", "Hatfield", "Astronomy", 2.76);
INSERT INTO student VALUES(2289, "Marguerite", "Mata", "Animation", 2.21);
INSERT INTO student VALUES(2475, "Grant", "Mullins", "Physics", 3.5);
INSERT INTO student VALUES(2725, "Grant", "Montgomery", "Electrical and Electronics Engineering", 3.54);
INSERT INTO student VALUES(3006, "Aiden", "Stanton", "Music", 3.58);
INSERT INTO student VALUES(9086, "Byron", "James", "Physics", 2.53);
INSERT INTO student VALUES(2477, "Louis", "Maxwell", "Architecture", 2.9);
INSERT INTO student VALUES(9350, "Clark", "Dodson", "Economics", 3.17);
INSERT INTO student VALUES(1973, "Cameron", "Garcia", "Biology", 2.74);
INSERT INTO student VALUES(3665, "Isaiah", "Young", "Economics", 2.44);
INSERT INTO student VALUES(7703, "Nevin", "Haas", "Business Administration", 3.19);
INSERT INTO student VALUES(1788, "Kylie", "Mcbride", "Economics", 3.52);
INSERT INTO student VALUES(8208, "Anneliese", "Alexander", "Electrical and Electronics Engineering", 2.51);
INSERT INTO student VALUES(9796, "Cerise", "Little", "International Trade and Finance", 2.04);
INSERT INTO student VALUES(3735, "Cash", "Palmer", "Astronomy", 3.93);
INSERT INTO student VALUES(6210, "Jeremy", "Kramer", "Astronomy", 2.8);
INSERT INTO student VALUES(9866, "Preston", "Delgado", "Logistics Management", 2.2);
INSERT INTO student VALUES(1637, "Rylie", "Jones", "Industrial Engineering", 2.72);
INSERT INTO student VALUES(6515, "Louis", "Calhoun", "Mathematics", 1.81);
INSERT INTO student VALUES(3416, "Vernon", "Chaney", "Energy Systems Engineering", 4.0);
INSERT INTO student VALUES(7913, "Taylore", "Cooley", "Architecture", 2.35);
INSERT INTO student VALUES(4853, "Heath", "Carroll", "Business Administration", 2.99);
INSERT INTO student VALUES(5747, "Sheridan", "Hinton", "Economics", 3.92);
INSERT INTO student VALUES(5211, "Garrison", "Sanchez", "Physics", 1.94);
INSERT INTO student VALUES(5438, "Adele", "Cisneros", "Chemistry", 3.29);
INSERT INTO student VALUES(2185, "Myron", "Riddle", "Animation", 2.15);
INSERT INTO student VALUES(7315, "Zane", "Peterson", "Graphic Design", 3.01);
INSERT INTO student VALUES(8111, "Taylore", "Ross", "Physics", 2.0);
INSERT INTO student VALUES(1140, "Wade", "Oconnell", "Astronomy", 3.07);
INSERT INTO student VALUES(2339, "Doran", "Bolton", "Mechanical Engineering", 3.08);
INSERT INTO student VALUES(6553, "Eloise", "Kramer", "Electrical and Electronics Engineering", 3.31);
INSERT INTO student VALUES(8636, "Heath", "Davidson", "Film Design", 1.8);
INSERT INTO student VALUES(4273, "Anise", "Mooney", "Chemistry", 3.94);
INSERT INTO student VALUES(4589, "Cameron", "Fuller", "Civil Engineering", 3.45);
INSERT INTO student VALUES(2709, "Annabel", "Larson", "Animation", 3.47);
INSERT INTO student VALUES(3562, "Riley", "Mcdowell", "Mechanical Engineering", 2.64);
INSERT INTO student VALUES(4276, "Reese", "Rivera", "Graphic Design", 2.63);
INSERT INTO student VALUES(3998, "Ellison", "Curtis", "Film Design", 1.98);
INSERT INTO student VALUES(5712, "Carelyn", "Cunningham", "Physics", 2.0);
INSERT INTO student VALUES(2885, "Anthony", "Berg", "Mathematics", 2.48);
INSERT INTO student VALUES(6477, "Vernon", "Moss", "Civil Engineering", 3.13);
INSERT INTO student VALUES(8484, "Georgina", "Bernard", "Chemistry", 1.82);
INSERT INTO student VALUES(5726, "Leonie", "Murray", "Economics", 3.7);
INSERT INTO student VALUES(4490, "Coralie", "Burgess", "Industrial Engineering", 2.39);
INSERT INTO student VALUES(2178, "Fawn", "Cisneros", "Music", 3.66);
INSERT INTO student VALUES(8441, "Coreen", "Middleton", "Biology", 3.58);
INSERT INTO student VALUES(2599, "Kate", "Frey", "Mathematics", 3.37);
INSERT INTO student VALUES(4856, "Marcella", "David", "Economics", 2.95);
INSERT INTO student VALUES(8381, "Brooke", "Vance", "Chemistry", 3.13);
INSERT INTO student VALUES(5542, "Troy", "Oconnell", "Software Engineering", 2.08);
INSERT INTO student VALUES(3697, "Georgina", "Hardy", "Physics", 2.25);
INSERT INTO student VALUES(1091, "Haiden", "Valenzuela", "Architecture", 3.35);
INSERT INTO student VALUES(5260, "Jeremy", "Ritter", "Civil Engineering", 3.49);
INSERT INTO student VALUES(8890, "Monteen", "Sims", "Software Engineering", 3.74);
INSERT INTO student VALUES(3064, "Rayleen", "Powell", "Industrial Engineering", 3.75);
INSERT INTO student VALUES(8606, "Isaac", "Gross", "Electrical and Electronics Engineering", 2.77);
INSERT INTO student VALUES(4798, "Berlynn", "Fuller", "International Trade and Finance", 3.71);
INSERT INTO student VALUES(5814, "Carleen", "Mcbride", "Film Design", 3.01);
INSERT INTO student VALUES(8080, "Vanessa", "Dalton", "Physics", 3.41);
INSERT INTO student VALUES(3722, "Rene", "Gonzalez", "International Trade and Finance", 3.09);
INSERT INTO student VALUES(1519, "Zachary", "Avery", "Mechanical Engineering", 3.81);
INSERT INTO student VALUES(1170, "Bree", "Greene", "Electrical and Electronics Engineering", 1.8);
INSERT INTO student VALUES(3667, "Thomas", "Holmes", "Civil Engineering", 1.86);
INSERT INTO student VALUES(4844, "Haiden", "Zuniga", "Music", 2.02);
INSERT INTO student VALUES(8662, "Shane", "Burton", "Music", 2.59);
INSERT INTO student VALUES(7697, "Caren", "Barker", "Astronomy", 3.1);
INSERT INTO student VALUES(1916, "Malachi", "Wade", "Animation", 2.94);
INSERT INTO student VALUES(8935, "Jack", "Shepherd", "Graphic Design", 2.8);
INSERT INTO student VALUES(4372, "Blake", "Sellers", "International Trade and Finance", 2.05);
INSERT INTO student VALUES(2581, "Avery", "Stanton", "Software Engineering", 1.79);
INSERT INTO student VALUES(8781, "Rebecca", "Best", "Architecture", 3.44);
INSERT INTO student VALUES(3096, "Gregory", "Cunningham", "Software Engineering", 3.0);
INSERT INTO student VALUES(5580, "Alice", "Duran", "Economics", 2.82);
INSERT INTO student VALUES(1776, "Verena", "Osborne", "Physics", 2.59);
INSERT INTO student VALUES(6270, "Riley", "Madden", "Software Engineering", 2.86);
INSERT INTO student VALUES(7065, "Hollyn", "Gillespie", "Film Design", 2.04);
INSERT INTO student VALUES(5167, "Michael", "Carr", "Computer Engineering", 1.78);
INSERT INTO student VALUES(6956, "Marcellus", "Burns", "Graphic Design", 1.95);
INSERT INTO student VALUES(8261, "Abigail", "Nunez", "Music", 3.4);
INSERT INTO student VALUES(2157, "Myron", "Lopez", "International Trade and Finance", 2.9);
INSERT INTO student VALUES(4558, "Monteen", "Lamb", "Industrial Engineering", 2.78);
INSERT INTO student VALUES(7590, "Josiah", "Miller", "Mechanical Engineering", 2.62);
INSERT INTO student VALUES(4984, "Marcellus", "Vazquez", "Graphic Design", 2.95);
INSERT INTO student VALUES(6200, "Korin", "Henry", "International Trade and Finance", 2.95);
INSERT INTO student VALUES(2646, "Vivian", "Branch", "Industrial Design", 2.41);
INSERT INTO student VALUES(3484, "Dante", "Werner", "Industrial Design", 2.9);
INSERT INTO student VALUES(5970, "Bianca", "Gillespie", "Electrical and Electronics Engineering", 2.93);
INSERT INTO student VALUES(5391, "Matteo", "Horn", "Electrical and Electronics Engineering", 2.63);
INSERT INTO student VALUES(1323, "Ellen", "Henderson", "Biology", 3.62);
INSERT INTO student VALUES(3737, "Carmden", "Haney", "Mechanical Engineering", 3.76);
INSERT INTO student VALUES(3813, "Madisen", "Best", "Economics", 1.87);
INSERT INTO student VALUES(6919, "Rene", "Rodriguez", "Energy Systems Engineering", 2.43);
INSERT INTO student VALUES(8109, "Oren", "Velez", "Biology", 1.78);
INSERT INTO student VALUES(6549, "Evelyn", "Barnett", "Film Design", 2.2);
INSERT INTO student VALUES(2254, "Berlynn", "Ware", "Industrial Engineering", 2.89);
INSERT INTO student VALUES(4464, "Benjamin", "Wilkinson", "Graphic Design", 2.92);
INSERT INTO student VALUES(5937, "Marcella", "Dyer", "Logistics Management", 2.15);
INSERT INTO student VALUES(2385, "Hope", "Rodgers", "Physics", 3.97);
INSERT INTO student VALUES(2634, "Murphy", "Nixon", "Computer Engineering", 3.66);
INSERT INTO student VALUES(8588, "Heath", "Lynn", "Music", 3.82);
INSERT INTO student VALUES(9594, "Marcella", "Orozco", "Physics", 2.94);
INSERT INTO student VALUES(7387, "Brock", "Hunter", "Software Engineering", 2.78);
INSERT INTO student VALUES(8084, "Vivian", "Haynes", "International Trade and Finance", 2.04);
INSERT INTO student VALUES(5056, "Matteo", "Guerrero", "Energy Systems Engineering", 3.3);
INSERT INTO student VALUES(1862, "Paul", "Burke", "Mechanical Engineering", 2.76);
INSERT INTO student VALUES(9905, "Joanna", "Hanson", "Music", 2.3);
INSERT INTO student VALUES(3053, "Anneliese", "Landry", "Film Design", 3.05);
INSERT INTO student VALUES(3074, "Zoe", "Walton", "Film Design", 2.99);
INSERT INTO student VALUES(6485, "Timothy", "Gray", "Astronomy", 2.08);
INSERT INTO student VALUES(9162, "Karilyn", "Rojas", "Computer Engineering", 2.03);
INSERT INTO student VALUES(2656, "Tobias", "Cisneros", "Business Administration", 2.09);
INSERT INTO student VALUES(6070, "Vanessa", "Holland", "Energy Systems Engineering", 2.11);
INSERT INTO student VALUES(2827, "Mae", "Beard", "International Trade and Finance", 3.46);
INSERT INTO student VALUES(2426, "Anneliese", "Butler", "Logistics Management", 3.73);
INSERT INTO student VALUES(7892, "Marcella", "Murillo", "Mechanical Engineering", 3.6);
INSERT INTO student VALUES(9066, "Dawn", "Harvey", "Physics", 2.6);
INSERT INTO student VALUES(6157, "Kate", "Ellison", "Electrical and Electronics Engineering", 2.53);
INSERT INTO student VALUES(1883, "Josiah", "Donaldson", "Electrical and Electronics Engineering", 1.93);
INSERT INTO student VALUES(4095, "Jolee", "Saunders", "International Trade and Finance", 2.81);
INSERT INTO student VALUES(3339, "Blake", "Maxwell", "Electrical and Electronics Engineering", 1.82);
INSERT INTO student VALUES(1678, "Jaidyn", "Malone", "Astronomy", 2.64);
INSERT INTO student VALUES(8910, "Lawrence", "Jones", "Software Engineering", 2.79);
INSERT INTO student VALUES(9033, "Jackson", "Mack", "Business Administration", 2.62);
INSERT INTO student VALUES(5307, "Candice", "Winters", "Business Administration", 2.46);
INSERT INTO student VALUES(6542, "Ellice", "Mills", "Mathematics", 3.49);
INSERT INTO student VALUES(4349, "Nevin", "Francis", "Computer Engineering", 1.81);
INSERT INTO student VALUES(6958, "Byron", "Snow", "Animation", 1.97);
INSERT INTO student VALUES(4012, "Kaitlin", "Harmon", "Logistics Management", 2.46);
INSERT INTO student VALUES(6124, "Lynn", "Johnson", "Physics", 3.23);
INSERT INTO student VALUES(2836, "Abraham", "Randolph", "Astronomy", 2.75);
INSERT INTO student VALUES(1226, "Porter", "Walsh", "Graphic Design", 3.32);
INSERT INTO student VALUES(4179, "Julian", "Pineda", "Industrial Design", 2.91);
INSERT INTO student VALUES(4835, "Oscar", "Scott", "Architecture", 3.59);
INSERT INTO student VALUES(3046, "Bernice", "Ross", "Mechanical Engineering", 2.25);
INSERT INTO student VALUES(2431, "Edward", "Hartman", "Economics", 1.76);
INSERT INTO student VALUES(2592, "Seth", "Cherry", "Industrial Design", 3.13);
INSERT INTO student VALUES(5770, "Orlando", "Allen", "Architecture", 2.91);
INSERT INTO student VALUES(4509, "Kai", "Edwards", "Architecture", 3.84);
INSERT INTO student VALUES(7839, "Leo", "Horn", "Biology", 3.58);
INSERT INTO student VALUES(8049, "Robert", "Rodriguez", "Computer Engineering", 1.84);
INSERT INTO student VALUES(3521, "Merle", "Nichols", "International Trade and Finance", 2.36);
INSERT INTO student VALUES(2724, "Ann", "Macdonald", "Computer Engineering", 3.26);
INSERT INTO student VALUES(8727, "Coralie", "Holloway", "Electrical and Electronics Engineering", 3.21);
INSERT INTO student VALUES(3336, "Matteo", "Mckee", "Mathematics", 2.09);
INSERT INTO student VALUES(2639, "Justice", "Braun", "Chemistry", 1.93);
INSERT INTO student VALUES(7941, "Rebecca", "Hood", "International Trade and Finance", 2.17);
INSERT INTO student VALUES(7795, "Hollyn", "Cordova", "Business Administration", 3.15);
INSERT INTO student VALUES(2197, "Oscar", "Melton", "Computer Engineering", 2.73);
INSERT INTO student VALUES(7664, "Arthur", "Sandoval", "Civil Engineering", 3.76);
INSERT INTO student VALUES(9541, "Silvia", "Leonard", "Computer Engineering", 2.78);
INSERT INTO student VALUES(3720, "Elias", "Sutton", "Chemistry", 2.47);
INSERT INTO student VALUES(1877, "Eloise", "Salas", "Chemistry", 3.86);
INSERT INTO student VALUES(3322, "Cameron", "Farmer", "Industrial Design", 1.83);
INSERT INTO student VALUES(7909, "June", "Velasquez", "Architecture", 3.8);
INSERT INTO student VALUES(5284, "Nadeen", "Vazquez", "Electrical and Electronics Engineering", 3.14);
INSERT INTO student VALUES(7487, "Lawrence", "Henry", "Chemistry", 3.82);
INSERT INTO student VALUES(9833, "Olive", "Morton", "Business Administration", 3.77);
INSERT INTO student VALUES(2112, "Vivian", "Jennings", "Biology", 3.87);
INSERT INTO student VALUES(7634, "Viola", "Gallegos", "Computer Engineering", 3.18);
INSERT INTO student VALUES(2200, "Anthony", "Day", "Graphic Design", 3.06);
INSERT INTO student VALUES(7538, "Paul", "Huffman", "Astronomy", 3.96);
INSERT INTO student VALUES(1173, "Varian", "Giles", "Astronomy", 3.61);
INSERT INTO student VALUES(2483, "Brett", "Case", "Animation", 3.29);
INSERT INTO student VALUES(2540, "Brandt", "Pope", "Biology", 2.67);
INSERT INTO student VALUES(4497, "Arden", "Kelley", "Architecture", 3.29);
INSERT INTO student VALUES(6492, "Caylen", "Harrell", "Industrial Design", 2.73);
INSERT INTO student VALUES(4470, "Erin", "York", "Logistics Management", 3.9);
INSERT INTO student VALUES(6025, "Nicolas", "Whitehead", "Logistics Management", 2.87);
INSERT INTO student VALUES(7281, "Bree", "Chambers", "Film Design", 2.63);
INSERT INTO student VALUES(4694, "Jasper", "Singh", "Biology", 3.82);
INSERT INTO student VALUES(7870, "Zachary", "Macdonald", "Business Administration", 2.15);
INSERT INTO student VALUES(4429, "Brendon", "Solis", "Music", 3.87);
INSERT INTO student VALUES(8750, "Dawn", "Oconnor", "Energy Systems Engineering", 1.89);
INSERT INTO student VALUES(9715, "Berlynn", "Noble", "Software Engineering", 2.2);
INSERT INTO student VALUES(1919, "Varian", "Mitchell", "Mechanical Engineering", 3.92);
INSERT INTO student VALUES(6786, "Haiden", "Clements", "Animation", 2.2);
INSERT INTO student VALUES(7416, "Eli", "Shea", "Chemistry", 3.46);
INSERT INTO student VALUES(4528, "Robin", "Peterson", "Business Administration", 2.96);
INSERT INTO student VALUES(8726, "Vivian", "Johnson", "Architecture", 3.12);
INSERT INTO student VALUES(8506, "Blayne", "Chandler", "Mathematics", 3.45);
INSERT INTO student VALUES(1585, "Claudia", "Andrade", "Energy Systems Engineering", 2.89);
INSERT INTO student VALUES(8722, "Noah", "Huerta", "Animation", 1.97);
INSERT INTO student VALUES(8862, "Varian", "Christian", "Chemistry", 2.42);
INSERT INTO student VALUES(3383, "Kalan", "Bradshaw", "Business Administration", 2.54);
INSERT INTO student VALUES(9748, "William", "Coffey", "Civil Engineering", 2.2);
INSERT INTO student VALUES(5025, "Elodie", "Fritz", "Electrical and Electronics Engineering", 3.11);
INSERT INTO student VALUES(3711, "Rylie", "Malone", "Film Design", 3.85);
INSERT INTO student VALUES(2982, "Haiden", "Griffin", "Graphic Design", 1.89);
INSERT INTO student VALUES(2364, "Gwendolen", "Bowers", "Business Administration", 2.25);
INSERT INTO student VALUES(8288, "Zion", "Mccarty", "Animation", 2.24);
INSERT INTO student VALUES(5162, "Kathryn", "Lowe", "Mechanical Engineering", 2.69);
INSERT INTO student VALUES(9930, "Oliver", "Vega", "Electrical and Electronics Engineering", 2.95);
INSERT INTO student VALUES(3432, "Jackson", "Blake", "Software Engineering", 3.66);
INSERT INTO student VALUES(9952, "Marguerite", "Daugherty", "Software Engineering", 3.63);
INSERT INTO student VALUES(3565, "Blair", "Bell", "Industrial Design", 2.12);
INSERT INTO student VALUES(2750, "Sophia", "Shah", "Software Engineering", 2.33);
INSERT INTO student VALUES(2142, "Dex", "Conway", "Industrial Design", 3.81);
INSERT INTO student VALUES(1846, "Love", "Clements", "Logistics Management", 1.81);
INSERT INTO student VALUES(3424, "Allison", "Walter", "Economics", 3.47);
INSERT INTO student VALUES(5246, "Caleb", "Lamb", "Logistics Management", 3.05);
INSERT INTO student VALUES(3304, "Merle", "Pope", "Mechanical Engineering", 2.98);
INSERT INTO student VALUES(6817, "Claudia", "Koch", "Civil Engineering", 2.13);
INSERT INTO student VALUES(6525, "Wade", "Casey", "Physics", 3.25);
INSERT INTO student VALUES(6096, "Jane", "Price", "Biology", 3.28);
INSERT INTO student VALUES(5968, "Jeremy", "Compton", "Graphic Design", 2.25);
INSERT INTO student VALUES(9207, "Hugh", "Luna", "Music", 2.95);
INSERT INTO student VALUES(7099, "Tyson", "Patterson", "International Trade and Finance", 2.42);
INSERT INTO student VALUES(3949, "Damon", "Morgan", "Graphic Design", 3.73);
INSERT INTO student VALUES(6614, "Ann", "Stokes", "Architecture", 2.55);
INSERT INTO student VALUES(3274, "Bailee", "Nichols", "Business Administration", 2.33);
INSERT INTO student VALUES(5553, "Kent", "Koch", "Electrical and Electronics Engineering", 3.92);
INSERT INTO student VALUES(3902, "Harriet", "Garner", "Architecture", 1.89);
INSERT INTO student VALUES(6300, "Wade", "Mathews", "Graphic Design", 2.55);
INSERT INTO student VALUES(7942, "Preston", "Potts", "Logistics Management", 2.87);
INSERT INTO student VALUES(4845, "Naveen", "Kidd", "Chemistry", 1.78);
INSERT INTO student VALUES(9978, "Robert", "Sloan", "Chemistry", 3.88);
INSERT INTO student VALUES(2852, "Zachary", "Best", "Architecture", 1.92);
INSERT INTO student VALUES(1975, "Madeleine", "Bowman", "Mechanical Engineering", 3.49);
INSERT INTO student VALUES(5680, "David", "Kelley", "Biology", 1.99);
INSERT INTO student VALUES(5455, "Reeve", "Mccoy", "Electrical and Electronics Engineering", 2.39);
INSERT INTO student VALUES(5682, "Adelaide", "Carrillo", "Music", 3.35);
INSERT INTO student VALUES(4875, "Karilyn", "Fields", "Astronomy", 3.5);
INSERT INTO student VALUES(5526, "Brooke", "Werner", "Biology", 3.02);
INSERT INTO student VALUES(2320, "Kae", "Meza", "Software Engineering", 2.46);
INSERT INTO student VALUES(9791, "Coy", "Leblanc", "Mathematics", 2.87);
INSERT INTO student VALUES(5043, "Love", "Stevens", "Industrial Engineering", 2.79);
INSERT INTO student VALUES(7631, "Breean", "Mora", "Electrical and Electronics Engineering", 3.15);
INSERT INTO student VALUES(6735, "Joseph", "Chen", "Computer Engineering", 3.64);
INSERT INTO student VALUES(7748, "Rosalind", "Hensley", "Industrial Engineering", 2.13);
INSERT INTO student VALUES(6218, "Evony", "Chan", "Astronomy", 3.53);
INSERT INTO student VALUES(6520, "Jack", "Abbott", "Industrial Design", 3.52);
INSERT INTO student VALUES(8692, "Amelia", "Bowen", "Mathematics", 2.73);
INSERT INTO student VALUES(2496, "Matteo", "Diaz", "International Trade and Finance", 3.79);
INSERT INTO student VALUES(2448, "William", "Golden", "Mathematics", 3.88);
INSERT INTO student VALUES(8690, "Kate", "Bowen", "Biology", 2.65);
INSERT INTO student VALUES(6348, "Reese", "Roth", "Software Engineering", 3.48);
INSERT INTO student VALUES(6441, "Orlando", "Cunningham", "Biology", 3.95);
INSERT INTO student VALUES(6882, "Anneliese", "Cabrera", "Physics", 3.69);
INSERT INTO student VALUES(5842, "Shane", "Chan", "Industrial Design", 2.27);
INSERT INTO student VALUES(5709, "Sullivan", "Hudson", "Software Engineering", 3.58);
INSERT INTO student VALUES(9115, "Oscar", "Kane", "Film Design", 2.91);
INSERT INTO student VALUES(2498, "Cody", "Wong", "Mathematics", 2.4);
INSERT INTO student VALUES(7426, "Lynn", "Dominguez", "Biology", 3.96);
INSERT INTO student VALUES(2604, "Bianca", "Melendez", "Music", 2.05);
INSERT INTO student VALUES(8546, "Rylie", "Fritz", "Music", 2.34);
INSERT INTO student VALUES(9966, "Kate", "Melton", "Astronomy", 2.62);
INSERT INTO student VALUES(2195, "Naomi", "Vaughn", "Astronomy", 3.8);
INSERT INTO student VALUES(5140, "Carlen", "Mcmahon", "Animation", 2.28);
INSERT INTO student VALUES(2389, "Brooke", "Chan", "Logistics Management", 1.95);
INSERT INTO student VALUES(5997, "Gillian", "Rosales", "Logistics Management", 3.95);
INSERT INTO student VALUES(5989, "Hollyn", "Myers", "Logistics Management", 3.88);
INSERT INTO student VALUES(1896, "Quintin", "Porter", "Business Administration", 2.01);
INSERT INTO student VALUES(6713, "Rene", "Oconnor", "Music", 2.39);
INSERT INTO student VALUES(8438, "Robert", "Rocha", "Film Design", 2.19);
INSERT INTO student VALUES(3896, "Ellice", "Mccann", "Mechanical Engineering", 3.58);
INSERT INTO student VALUES(7599, "Hollyn", "Reilly", "Mechanical Engineering", 2.07);
INSERT INTO student VALUES(9836, "Susannah", "Cisneros", "Industrial Engineering", 3.07);
INSERT INTO student VALUES(6228, "Zane", "Neal", "Graphic Design", 3.12);
INSERT INTO student VALUES(5292, "Miriam", "Ho", "Economics", 2.05);
INSERT INTO student VALUES(6573, "Clelia", "Castaneda", "Mathematics", 3.89);
INSERT INTO student VALUES(6532, "Breean", "Conway", "International Trade and Finance", 3.66);
INSERT INTO student VALUES(6443, "Harriet", "Schmidt", "Astronomy", 3.79);
INSERT INTO student VALUES(1128, "Merle", "Buckley", "Mechanical Engineering", 3.17);
INSERT INTO student VALUES(9934, "Rory", "Mcmillan", "Mathematics", 2.54);
INSERT INTO student VALUES(8042, "Annabel", "Chan", "Animation", 3.29);
INSERT INTO student VALUES(6307, "Coralie", "Richmond", "Chemistry", 3.09);
INSERT INTO student VALUES(2183, "Rory", "Pena", "Electrical and Electronics Engineering", 3.88);
INSERT INTO student VALUES(6846, "Jasper", "Mcbride", "Computer Engineering", 2.26);
INSERT INTO student VALUES(1944, "Riley", "Petty", "Graphic Design", 3.88);
INSERT INTO student VALUES(5369, "Natalie", "Rios", "Animation", 3.33);
INSERT INTO student VALUES(2149, "Dante", "Garrison", "Film Design", 2.29);
INSERT INTO student VALUES(2867, "Quintin", "Black", "Animation", 2.91);
INSERT INTO student VALUES(2631, "Susannah", "Dalton", "Software Engineering", 3.97);
INSERT INTO student VALUES(3770, "Rylie", "Taylor", "Industrial Design", 3.04);
INSERT INTO student VALUES(9565, "Bernice", "Soto", "Industrial Design", 3.17);
INSERT INTO student VALUES(7165, "Jack", "Shah", "Astronomy", 2.65);
INSERT INTO student VALUES(2271, "Brighton", "Fernandez", "Film Design", 2.37);
INSERT INTO student VALUES(7103, "Coralie", "Pacheco", "Physics", 3.94);
INSERT INTO student VALUES(5791, "Julian", "Shepherd", "Mathematics", 2.14);
INSERT INTO student VALUES(2909, "Naomi", "Nicholson", "Physics", 1.94);
INSERT INTO student VALUES(6245, "David", "Ayala", "Animation", 2.29);
INSERT INTO student VALUES(2062, "Annabel", "Hancock", "Biology", 3.51);
INSERT INTO student VALUES(4376, "Wade", "Reilly", "Chemistry", 3.64);
INSERT INTO student VALUES(5686, "Mae", "Wyatt", "Physics", 3.86);
INSERT INTO student VALUES(9129, "Julina", "Bean", "Industrial Engineering", 1.98);
INSERT INTO student VALUES(4701, "Heath", "Oneill", "Biology", 1.89);
INSERT INTO student VALUES(6310, "Will", "Porter", "Architecture", 2.72);
INSERT INTO student VALUES(7392, "Brooke", "Khan", "Energy Systems Engineering", 2.94);
INSERT INTO student VALUES(6187, "Viola", "Wilkinson", "Graphic Design", 2.52);
INSERT INTO student VALUES(4974, "Raven", "Bright", "Animation", 2.67);
INSERT INTO student VALUES(2832, "Shane", "Nguyen", "Architecture", 2.84);
INSERT INTO student VALUES(2986, "Viola", "Crosby", "Civil Engineering", 3.19);
INSERT INTO student VALUES(3273, "Warren", "Ashley", "Chemistry", 2.3);
INSERT INTO student VALUES(6871, "Ryder", "Durham", "Electrical and Electronics Engineering", 2.1);
INSERT INTO student VALUES(8009, "Noel", "Dickerson", "Graphic Design", 2.13);
INSERT INTO student VALUES(1778, "Justin", "Livingston", "Industrial Engineering", 3.96);
INSERT INTO student VALUES(7863, "Marcella", "Horne", "Chemistry", 1.93);
INSERT INTO student VALUES(7237, "Emeline", "Hanson", "Mechanical Engineering", 2.46);
INSERT INTO student VALUES(2014, "Caleb", "Cisneros", "Chemistry", 3.18);
INSERT INTO student VALUES(7453, "Jack", "Klein", "Biology", 3.82);
INSERT INTO student VALUES(5749, "Dustin", "Donovan", "Industrial Design", 3.36);
INSERT INTO student VALUES(6785, "Lucinda", "Riddle", "Software Engineering", 3.27);
INSERT INTO student VALUES(3575, "Verena", "Bradford", "Civil Engineering", 3.33);
INSERT INTO student VALUES(4418, "Leonie", "Mason", "Electrical and Electronics Engineering", 3.25);
INSERT INTO student VALUES(9981, "Preston", "Patton", "Civil Engineering", 2.28);
INSERT INTO student VALUES(6148, "Dominick", "Costa", "Industrial Engineering", 2.07);
INSERT INTO student VALUES(6411, "Caylen", "Pace", "Physics", 2.66);
INSERT INTO student VALUES(4259, "Fawn", "Lucero", "Music", 3.05);
INSERT INTO student VALUES(8905, "Bailee", "Rogers", "Graphic Design", 3.05);
INSERT INTO student VALUES(4613, "Hope", "Rollins", "Industrial Design", 3.27);
INSERT INTO student VALUES(9792, "Jane", "Faulkner", "Music", 2.09);
INSERT INTO student VALUES(7365, "Denver", "Terry", "Industrial Design", 1.89);
INSERT INTO student VALUES(6740, "Susannah", "Schultz", "Economics", 3.61);
INSERT INTO student VALUES(7620, "Hollyn", "Burns", "Astronomy", 3.66);
INSERT INTO student VALUES(6032, "Tyson", "Cohen", "Energy Systems Engineering", 1.91);
INSERT INTO student VALUES(7691, "Tristan", "Saunders", "Computer Engineering", 3.23);
INSERT INTO student VALUES(7193, "Madeleine", "Mcneil", "Animation", 3.37);
INSERT INTO student VALUES(6233, "Denise", "Forbes", "Film Design", 3.65);
INSERT INTO student VALUES(4026, "Carelyn", "Roman", "International Trade and Finance", 3.89);
INSERT INTO student VALUES(1591, "Ellice", "Fry", "International Trade and Finance", 2.73);
INSERT INTO student VALUES(8909, "Conrad", "Reynolds", "Astronomy", 2.76);
INSERT INTO student VALUES(6900, "Oliver", "Phelps", "Astronomy", 3.15);
INSERT INTO student VALUES(4640, "Emeline", "Stephens", "Software Engineering", 3.43);
INSERT INTO student VALUES(2866, "Anthony", "Melendez", "Animation", 2.26);
INSERT INTO student VALUES(6369, "Nadeen", "Davila", "Mechanical Engineering", 2.57);
INSERT INTO student VALUES(6291, "Francis", "Montes", "Biology", 3.17);
INSERT INTO student VALUES(4436, "Cash", "Walsh", "Civil Engineering", 2.45);
INSERT INTO student VALUES(3179, "Amity", "Blanchard", "Energy Systems Engineering", 3.47);
INSERT INTO student VALUES(3815, "Linnea", "Li", "Software Engineering", 2.35);
INSERT INTO student VALUES(7458, "Sutton", "Flynn", "Astronomy", 3.42);
INSERT INTO student VALUES(3752, "Brighton", "Haas", "Industrial Engineering", 3.44);
INSERT INTO student VALUES(8100, "Javan", "Mcdowell", "Physics", 2.77);
INSERT INTO student VALUES(1276, "Ellory", "Potts", "Mathematics", 3.9);
INSERT INTO student VALUES(7107, "Orlando", "Atkins", "Industrial Engineering", 3.44);
INSERT INTO student VALUES(9598, "Vanessa", "Good", "Logistics Management", 2.07);
INSERT INTO student VALUES(6267, "Henry", "Carr", "Music", 3.23);
INSERT INTO student VALUES(6723, "Lynn", "Christensen", "Biology", 3.45);
INSERT INTO student VALUES(2947, "Joan", "Holloway", "Energy Systems Engineering", 3.46);
INSERT INTO student VALUES(2363, "Carleen", "Woodward", "Film Design", 2.7);
INSERT INTO student VALUES(2324, "Brendon", "Schmidt", "Architecture", 2.24);
INSERT INTO student VALUES(3936, "Preston", "Hines", "Mathematics", 3.16);
INSERT INTO student VALUES(9421, "Varian", "Scott", "Logistics Management", 3.09);
INSERT INTO student VALUES(8696, "Timothy", "Stephens", "Astronomy", 2.64);
INSERT INTO student VALUES(6888, "Adelaide", "Bolton", "Astronomy", 2.92);
INSERT INTO student VALUES(5451, "Syllable", "Beard", "Economics", 2.45);
INSERT INTO student VALUES(5986, "Trey", "Horn", "Software Engineering", 3.86);
INSERT INTO student VALUES(7058, "Drake", "Bradley", "Computer Engineering", 2.55);
INSERT INTO student VALUES(4056, "Caprice", "Friedman", "Architecture", 2.05);
INSERT INTO student VALUES(4067, "Lucinda", "Hanson", "Energy Systems Engineering", 3.47);
INSERT INTO student VALUES(7423, "Allison", "Boyd", "Astronomy", 2.25);
INSERT INTO student VALUES(7180, "Anthony", "Andrews", "Industrial Design", 3.0);
INSERT INTO student VALUES(8421, "Eli", "Poole", "Industrial Design", 2.11);
INSERT INTO student VALUES(4881, "Carmden", "Richard", "Industrial Engineering", 2.59);
INSERT INTO student VALUES(3828, "Annabel", "Dickson", "Mechanical Engineering", 3.36);
INSERT INTO student VALUES(2689, "Natalie", "Fry", "Mechanical Engineering", 1.85);
INSERT INTO student VALUES(4159, "Blair", "Zavala", "Physics", 3.01);
INSERT INTO student VALUES(1924, "Justice", "Guerra", "Mathematics", 2.38);
INSERT INTO student VALUES(8561, "Jaidyn", "Potter", "Astronomy", 2.52);
INSERT INTO student VALUES(4584, "Kaitlin", "Rubio", "International Trade and Finance", 1.89);
INSERT INTO student VALUES(6185, "Krystan", "Santana", "Energy Systems Engineering", 2.87);
INSERT INTO student VALUES(1094, "Gavin", "Scott", "Logistics Management", 2.02);
INSERT INTO student VALUES(1476, "Vanessa", "Simmons", "Logistics Management", 2.9);
INSERT INTO student VALUES(7226, "Vincent", "Bush", "Mechanical Engineering", 1.98);
INSERT INTO student VALUES(5967, "Nadeen", "Huber", "Electrical and Electronics Engineering", 3.5);
INSERT INTO student VALUES(5817, "Silvia", "Avila", "Logistics Management", 2.69);
INSERT INTO student VALUES(4499, "Byron", "Ho", "International Trade and Finance", 3.98);
INSERT INTO student VALUES(6754, "Gregory", "Page", "Animation", 3.27);
INSERT INTO student VALUES(7915, "Krystan", "Skinner", "Economics", 3.16);
INSERT INTO student VALUES(3055, "Carleen", "Sanders", "Graphic Design", 3.19);
INSERT INTO student VALUES(3981, "Ray", "Lucero", "Computer Engineering", 3.71);
INSERT INTO student VALUES(1407, "Kingston", "Rodriguez", "Business Administration", 3.15);
INSERT INTO student VALUES(3573, "Paul", "Hill", "Animation", 2.92);
INSERT INTO student VALUES(3646, "Miranda", "Preston", "Biology", 3.82);
INSERT INTO student VALUES(9679, "Randall", "Stark", "Industrial Design", 2.22);
INSERT INTO student VALUES(6436, "Riley", "Chase", "Physics", 3.24);
INSERT INTO student VALUES(5170, "Tanner", "Stein", "Chemistry", 1.9);
INSERT INTO student VALUES(7585, "Aryn", "Miranda", "Industrial Design", 2.46);
INSERT INTO student VALUES(3160, "Debree", "Branch", "Chemistry", 3.16);
INSERT INTO student VALUES(4255, "Ocean", "Curry", "Animation", 1.96);
INSERT INTO student VALUES(9076, "Leonie", "Vang", "Graphic Design", 3.15);
INSERT INTO student VALUES(7520, "Blaise", "Schmidt", "Mechanical Engineering", 3.79);
INSERT INTO student VALUES(9602, "Meaghan", "Bolton", "Biology", 3.79);
INSERT INTO student VALUES(5316, "Joanna", "Lawson", "Mechanical Engineering", 3.51);
INSERT INTO student VALUES(6911, "Michael", "Clayton", "Electrical and Electronics Engineering", 2.61);
INSERT INTO student VALUES(3037, "Apollo", "Dickerson", "International Trade and Finance", 2.49);
INSERT INTO student VALUES(1942, "Drew", "Grimes", "Industrial Engineering", 3.52);
INSERT INTO student VALUES(2071, "Vincent", "Little", "Mathematics", 2.35);
INSERT INTO student VALUES(2053, "Amity", "Woodward", "Electrical and Electronics Engineering", 3.68);
INSERT INTO student VALUES(7673, "Preston", "Walsh", "Energy Systems Engineering", 2.44);
INSERT INTO student VALUES(2730, "Troy", "Clarke", "Music", 2.21);
INSERT INTO student VALUES(2803, "Hope", "Oneal", "Music", 2.18);
INSERT INTO student VALUES(1558, "Raine", "Santiago", "Economics", 2.92);
INSERT INTO student VALUES(6964, "Sean", "Martinez", "Animation", 3.65);
INSERT INTO student VALUES(3328, "Justin", "Chung", "International Trade and Finance", 2.36);
INSERT INTO student VALUES(2812, "Lillian", "Eaton", "Industrial Design", 3.2);
INSERT INTO student VALUES(3826, "Jax", "Byrd", "Film Design", 2.4);
INSERT INTO student VALUES(3784, "Jaidyn", "Vazquez", "Astronomy", 3.29);
INSERT INTO student VALUES(2555, "Xavier", "Chambers", "Business Administration", 2.9);
INSERT INTO student VALUES(2310, "Adele", "Carlson", "Animation", 3.98);
INSERT INTO student VALUES(3515, "Blake", "Wagner", "Physics", 3.27);
INSERT INTO student VALUES(1739, "Rory", "Steele", "Civil Engineering", 2.37);
INSERT INTO student VALUES(5359, "Joan", "Hodge", "Mathematics", 1.9);
INSERT INTO student VALUES(2391, "Hyrum", "Manning", "Physics", 2.23);
INSERT INTO student VALUES(8728, "Sean", "Orozco", "Economics", 3.41);
INSERT INTO student VALUES(4627, "Damien", "Price", "Biology", 3.03);
INSERT INTO student VALUES(6496, "Felix", "Sosa", "Industrial Engineering", 3.2);
INSERT INTO student VALUES(9902, "Bailee", "Mccarthy", "International Trade and Finance", 2.96);
INSERT INTO student VALUES(7388, "Gillian", "Marshall", "Film Design", 2.19);
INSERT INTO student VALUES(7142, "Sheridan", "Clements", "Mathematics", 2.58);
INSERT INTO student VALUES(9872, "Abe", "Fry", "Graphic Design", 2.92);
INSERT INTO student VALUES(6264, "Madisen", "Fuller", "Electrical and Electronics Engineering", 2.91);
INSERT INTO student VALUES(7906, "Gabriel", "Russo", "Industrial Engineering", 2.86);
INSERT INTO student VALUES(8650, "Sherleen", "Cohen", "Biology", 2.84);
INSERT INTO student VALUES(9474, "Felix", "Doyle", "Software Engineering", 2.29);
INSERT INTO student VALUES(6340, "Reese", "Waters", "Music", 3.23);
INSERT INTO student VALUES(5918, "Korin", "Sims", "Mathematics", 3.55);
INSERT INTO student VALUES(3903, "Doran", "Stevenson", "Film Design", 3.78);
INSERT INTO student VALUES(3482, "Emeline", "Jacobson", "Business Administration", 2.43);
INSERT INTO student VALUES(5488, "Julian", "Singh", "Physics", 3.15);
INSERT INTO student VALUES(9762, "Ellen", "Irwin", "Software Engineering", 2.06);
INSERT INTO student VALUES(4848, "Louisa", "Green", "Economics", 3.19);
INSERT INTO student VALUES(9637, "Robin", "Bass", "Energy Systems Engineering", 3.85);
INSERT INTO student VALUES(5274, "Ellice", "Meyer", "Economics", 3.62);
INSERT INTO student VALUES(3111, "Lynn", "Short", "Physics", 3.55);
INSERT INTO student VALUES(6563, "Oliver", "Winters", "Computer Engineering", 3.39);
INSERT INTO student VALUES(4591, "Lucinda", "Ibarra", "Business Administration", 2.59);
INSERT INTO student VALUES(8876, "Claude", "Holt", "Astronomy", 2.23);
INSERT INTO student VALUES(4391, "Apollo", "Savage", "Economics", 1.89);
INSERT INTO student VALUES(3821, "Quintin", "Bernard", "Mathematics", 3.18);
INSERT INTO student VALUES(7601, "Abraham", "Villarreal", "International Trade and Finance", 3.87);
INSERT INTO student VALUES(5629, "Sullivan", "Kramer", "Mechanical Engineering", 3.76);
INSERT INTO student VALUES(9402, "Dominick", "Christensen", "Industrial Engineering", 3.88);
INSERT INTO student VALUES(6701, "Murphy", "Gross", "Biology", 3.03);
INSERT INTO student VALUES(9562, "Coreen", "Ellison", "Music", 2.52);
INSERT INTO student VALUES(4463, "Sue", "Schwartz", "Software Engineering", 2.87);
INSERT INTO student VALUES(6355, "Amity", "Alvarado", "Physics", 2.7);
INSERT INTO student VALUES(4286, "Brock", "Cortez", "Logistics Management", 3.02);
INSERT INTO student VALUES(3363, "Hyrum", "Bolton", "Mathematics", 3.88);
INSERT INTO student VALUES(9747, "Kai", "Santos", "Mechanical Engineering", 3.57);
INSERT INTO student VALUES(1031, "Taylore", "Mcgee", "Economics", 2.63);
INSERT INTO student VALUES(9179, "Syllable", "Vega", "Music", 2.68);
INSERT INTO student VALUES(6568, "Malachi", "Villegas", "Electrical and Electronics Engineering", 2.38);
INSERT INTO student VALUES(4114, "Gavin", "Cherry", "Chemistry", 3.79);
INSERT INTO student VALUES(9699, "Vanessa", "Suarez", "Astronomy", 2.3);
INSERT INTO student VALUES(3966, "Oren", "Delgado", "Civil Engineering", 3.28);
INSERT INTO student VALUES(8549, "Coreen", "Shields", "Physics", 3.91);
INSERT INTO student VALUES(1763, "James", "Ryan", "Computer Engineering", 1.84);
INSERT INTO student VALUES(1332, "Fernando", "Salas", "Chemistry", 2.68);
INSERT INTO student VALUES(6657, "Cash", "Carlson", "Industrial Design", 2.08);
INSERT INTO student VALUES(2407, "Jude", "Tucker", "Civil Engineering", 2.05);
INSERT INTO student VALUES(2491, "Ocean", "Golden", "Architecture", 2.86);
INSERT INTO student VALUES(3066, "Josiah", "Hurst", "Mathematics", 2.55);
INSERT INTO student VALUES(9308, "Dawn", "Arias", "Biology", 3.28);
INSERT INTO student VALUES(9000, "Rayleen", "Gross", "Logistics Management", 3.58);
INSERT INTO student VALUES(7123, "Kylie", "Hill", "Chemistry", 2.48);
INSERT INTO student VALUES(3071, "Matilda", "Hood", "Music", 2.5);
INSERT INTO student VALUES(2502, "Jude", "Cohen", "Physics", 1.91);
INSERT INTO student VALUES(7055, "Evony", "Stone", "Electrical and Electronics Engineering", 3.58);
INSERT INTO student VALUES(6577, "Madisen", "Stout", "Physics", 3.16);
INSERT INTO student VALUES(4082, "Sophia", "Brown", "Industrial Engineering", 2.76);
INSERT INTO student VALUES(3288, "Elein", "Small", "Chemistry", 2.82);
INSERT INTO student VALUES(9490, "Brooke", "Osborne", "Electrical and Electronics Engineering", 2.35);
INSERT INTO student VALUES(2460, "Jeremy", "Crane", "Mathematics", 3.34);
INSERT INTO student VALUES(6279, "Julina", "Bradshaw", "Energy Systems Engineering", 2.09);
INSERT INTO student VALUES(9648, "Caren", "Chapman", "Astronomy", 2.81);
INSERT INTO student VALUES(2657, "Louis", "Bonilla", "Mathematics", 2.36);
INSERT INTO student VALUES(6106, "Aiden", "Erickson", "Graphic Design", 3.74);
INSERT INTO student VALUES(5616, "Noel", "Ali", "Computer Engineering", 3.13);
INSERT INTO student VALUES(4399, "Leonie", "Hale", "Business Administration", 3.08);
INSERT INTO student VALUES(5864, "Damon", "Hill", "Chemistry", 2.39);
INSERT INTO student VALUES(8120, "Cameron", "Andrade", "Animation", 3.83);
INSERT INTO student VALUES(6052, "Elodie", "Rice", "Animation", 2.65);
INSERT INTO student VALUES(2976, "Charles", "Roth", "Chemistry", 3.67);
INSERT INTO student VALUES(5527, "Coreen", "Best", "Graphic Design", 2.93);
INSERT INTO student VALUES(6842, "Fern", "Cochran", "Industrial Engineering", 1.8);
INSERT INTO student VALUES(5063, "Brandt", "Bates", "Architecture", 3.27);
INSERT INTO student VALUES(6134, "Justice", "Hickman", "Civil Engineering", 3.66);
INSERT INTO student VALUES(4419, "Tyson", "Ali", "Film Design", 2.44);
INSERT INTO student VALUES(4161, "Brock", "Ho", "Physics", 2.03);
INSERT INTO student VALUES(4716, "Hyrum", "Sexton", "Logistics Management", 2.32);
INSERT INTO student VALUES(6794, "Breean", "Salazar", "Civil Engineering", 2.33);
INSERT INTO student VALUES(6705, "Breean", "Mcknight", "Chemistry", 2.4);
INSERT INTO student VALUES(8537, "Kalan", "Cruz", "Film Design", 2.05);
INSERT INTO student VALUES(8762, "Emerson", "Mendez", "Logistics Management", 3.87);
INSERT INTO student VALUES(4808, "Eli", "Michael", "Chemistry", 3.89);
INSERT INTO student VALUES(5902, "Bram", "Herman", "Chemistry", 3.03);
INSERT INTO student VALUES(6236, "Meaghan", "Schaefer", "Industrial Engineering", 2.88);
INSERT INTO student VALUES(1587, "Jacklyn", "Beck", "Physics", 3.39);
INSERT INTO student VALUES(4518, "Jackson", "Baker", "Business Administration", 3.3);
INSERT INTO student VALUES(7935, "Ocean", "Mullins", "Graphic Design", 3.89);
INSERT INTO student VALUES(7683, "Glenn", "Little", "International Trade and Finance", 3.43);
INSERT INTO student VALUES(9891, "Abe", "Owens", "Astronomy", 2.69);
INSERT INTO student VALUES(7846, "Gregory", "Ali", "Mechanical Engineering", 2.65);
INSERT INTO student VALUES(4737, "Coralie", "Maldonado", "Logistics Management", 3.23);
INSERT INTO student VALUES(4515, "Blayne", "Murray", "International Trade and Finance", 2.68);
INSERT INTO student VALUES(3881, "Ricardo", "Church", "Industrial Engineering", 3.55);
INSERT INTO student VALUES(8645, "Xavier", "Moreno", "Energy Systems Engineering", 1.87);
INSERT INTO student VALUES(2840, "Damien", "Knox", "Industrial Design", 3.46);
INSERT INTO student VALUES(3233, "Ocean", "Dougherty", "Chemistry", 3.82);
INSERT INTO student VALUES(2321, "Coralie", "Clarke", "Mechanical Engineering", 3.21);
INSERT INTO student VALUES(5886, "Shane", "Gonzalez", "Logistics Management", 2.14);
INSERT INTO student VALUES(2068, "Susannah", "Mcintyre", "Music", 3.36);
INSERT INTO student VALUES(3692, "Brooke", "Leonard", "Mathematics", 3.15);
INSERT INTO student VALUES(6062, "Verena", "Jones", "Music", 3.08);
INSERT INTO student VALUES(8230, "Abraham", "Avery", "Chemistry", 1.79);
INSERT INTO student VALUES(1039, "Coy", "Steele", "Astronomy", 3.82);
INSERT INTO student VALUES(7650, "Dash", "Case", "Physics", 3.14);
INSERT INTO student VALUES(8560, "Louisa", "Harper", "Mathematics", 2.9);
INSERT INTO student VALUES(5367, "Korin", "Pollard", "Mechanical Engineering", 2.44);
INSERT INTO student VALUES(2814, "Madeleine", "Burton", "Business Administration", 1.81);
INSERT INTO student VALUES(2536, "Vincent", "Fleming", "Economics", 1.96);
INSERT INTO student VALUES(6724, "Jack", "Small", "Physics", 3.18);
INSERT INTO student VALUES(2213, "Isaac", "Greer", "Mechanical Engineering", 3.42);
INSERT INTO student VALUES(3272, "Oscar", "Stone", "Physics", 3.8);
INSERT INTO student VALUES(4797, "Henry", "Page", "Logistics Management", 1.89);
INSERT INTO student VALUES(3739, "Vernon", "Cuevas", "Animation", 2.75);
INSERT INTO student VALUES(2680, "Denver", "Owen", "Electrical and Electronics Engineering", 3.34);
INSERT INTO student VALUES(1781, "Matilda", "Vance", "Energy Systems Engineering", 2.56);
INSERT INTO student VALUES(1802, "Sherleen", "Dorsey", "International Trade and Finance", 2.05);
INSERT INTO student VALUES(3323, "William", "Long", "Film Design", 2.53);
INSERT INTO student VALUES(2344, "Silvia", "Vance", "International Trade and Finance", 2.4);
INSERT INTO student VALUES(2786, "Aryn", "Robinson", "Astronomy", 3.63);
INSERT INTO student VALUES(8456, "Bailee", "Clark", "Chemistry", 1.98);
INSERT INTO student VALUES(9875, "Zachary", "Sexton", "Biology", 3.23);
INSERT INTO student VALUES(2497, "Anise", "Ingram", "Economics", 2.34);
INSERT INTO student VALUES(3943, "Zane", "Kemp", "Electrical and Electronics Engineering", 3.04);
INSERT INTO student VALUES(1041, "Wade", "Chase", "Civil Engineering", 2.72);
INSERT INTO student VALUES(8564, "Lillian", "Dorsey", "Film Design", 1.84);
INSERT INTO student VALUES(9072, "Arden", "Cooley", "Graphic Design", 2.73);
INSERT INTO student VALUES(6827, "Devon", "Hill", "Animation", 3.26);
INSERT INTO student VALUES(8521, "Taye", "Vance", "Chemistry", 2.53);
INSERT INTO student VALUES(3200, "Mirabel", "Case", "Computer Engineering", 2.42);
INSERT INTO student VALUES(8825, "Sutton", "Franco", "Mechanical Engineering", 2.67);
INSERT INTO student VALUES(4334, "Brendon", "Walker", "Biology", 3.07);
INSERT INTO student VALUES(2641, "Dawn", "Rojas", "Mathematics", 3.07);
INSERT INTO student VALUES(1370, "Adelaide", "Cochran", "Mechanical Engineering", 3.06);
INSERT INTO student VALUES(6269, "Gillian", "Juarez", "Industrial Design", 2.22);
INSERT INTO student VALUES(6584, "Aiden", "Garner", "Mechanical Engineering", 3.57);
INSERT INTO student VALUES(8974, "Zoe", "Downs", "Energy Systems Engineering", 2.62);
INSERT INTO student VALUES(8013, "Taye", "Berry", "Electrical and Electronics Engineering", 2.65);
INSERT INTO student VALUES(8841, "Rose", "Hurst", "Electrical and Electronics Engineering", 3.56);
INSERT INTO student VALUES(3292, "David", "Leblanc", "Business Administration", 2.89);
INSERT INTO student VALUES(8547, "Caprice", "Villegas", "Economics", 2.74);
INSERT INTO student VALUES(6138, "Blake", "English", "Logistics Management", 2.37);
INSERT INTO student VALUES(1545, "Dante", "Shaffer", "Animation", 2.8);
INSERT INTO student VALUES(5515, "Korin", "Hines", "Logistics Management", 3.7);
INSERT INTO student VALUES(5618, "Clelia", "Price", "Astronomy", 3.79);
INSERT INTO student VALUES(2716, "Cameron", "Hoffman", "Energy Systems Engineering", 3.13);
INSERT INTO student VALUES(1386, "Sean", "Kane", "Physics", 3.82);
INSERT INTO student VALUES(6182, "Ryder", "Simon", "Logistics Management", 3.73);
INSERT INTO student VALUES(1222, "Doran", "Kaufman", "Industrial Engineering", 3.58);
INSERT INTO student VALUES(9338, "Javan", "Lloyd", "Biology", 3.81);
INSERT INTO student VALUES(5761, "Jeremy", "Gamble", "Physics", 3.91);
INSERT INTO student VALUES(8414, "Brendon", "Doyle", "Architecture", 2.65);
INSERT INTO student VALUES(6314, "Jae", "Sweeney", "Business Administration", 2.01);
INSERT INTO student VALUES(3545, "Zachary", "Gutierrez", "Software Engineering", 1.78);
INSERT INTO student VALUES(9470, "Blanche", "Silva", "Architecture", 2.11);
INSERT INTO student VALUES(6947, "Denise", "Carey", "Logistics Management", 2.37);
INSERT INTO student VALUES(5756, "Grant", "Roth", "Music", 3.17);
INSERT INTO student VALUES(1248, "Grey", "Underwood", "International Trade and Finance", 2.61);
INSERT INTO student VALUES(9570, "Brett", "Duran", "Business Administration", 2.3);
INSERT INTO student VALUES(2016, "Gavin", "Webb", "Music", 2.93);
INSERT INTO student VALUES(5085, "Noah", "Foley", "Energy Systems Engineering", 3.85);
INSERT INTO student VALUES(7289, "Rayleen", "Garrison", "Physics", 1.95);
INSERT INTO student VALUES(8953, "David", "Castaneda", "Physics", 1.96);
INSERT INTO student VALUES(9397, "Henry", "Wallace", "Electrical and Electronics Engineering", 1.78);
INSERT INTO student VALUES(1143, "Lillian", "Noble", "Film Design", 3.1);
INSERT INTO student VALUES(7092, "Merle", "Quinn", "Computer Engineering", 3.78);
INSERT INTO student VALUES(7682, "Javan", "Pittman", "Astronomy", 2.02);
INSERT INTO student VALUES(3962, "Byron", "Moran", "Graphic Design", 3.97);
INSERT INTO student VALUES(1964, "Will", "Elliott", "Chemistry", 2.99);
INSERT INTO student VALUES(2966, "Varian", "Pollard", "Chemistry", 3.75);
INSERT INTO student VALUES(7175, "Hollyn", "Case", "Industrial Engineering", 2.8);
INSERT INTO student VALUES(3937, "Drew", "Bradley", "Industrial Design", 3.88);
INSERT INTO student VALUES(9415, "Miranda", "Cunningham", "Industrial Design", 2.65);
INSERT INTO student VALUES(5614, "Allison", "Gilmore", "Graphic Design", 2.46);
INSERT INTO student VALUES(4834, "Jeremy", "Fritz", "Industrial Engineering", 3.98);
INSERT INTO student VALUES(3126, "William", "Clark", "Logistics Management", 2.42);
INSERT INTO student VALUES(7676, "Jaidyn", "Schaefer", "Music", 2.1);
INSERT INTO student VALUES(3536, "Korin", "Stafford", "Software Engineering", 3.22);
INSERT INTO student VALUES(9479, "Adelaide", "Harvey", "International Trade and Finance", 3.01);
INSERT INTO student VALUES(6795, "Gillian", "Mayo", "Software Engineering", 2.15);
INSERT INTO student VALUES(5280, "Miriam", "Keller", "Film Design", 1.98);
INSERT INTO student VALUES(2318, "Adele", "Good", "Animation", 3.3);
INSERT INTO student VALUES(5013, "Gillian", "Potts", "Music", 1.95);
INSERT INTO student VALUES(5587, "Susannah", "Navarro", "Physics", 2.8);
INSERT INTO student VALUES(5308, "Gregory", "Moody", "Architecture", 2.84);
INSERT INTO student VALUES(6620, "Jude", "Wilkins", "Architecture", 3.63);
INSERT INTO student VALUES(7643, "Coralie", "Rasmussen", "Mathematics", 2.88);
INSERT INTO student VALUES(5065, "Apollo", "Fernandez", "Energy Systems Engineering", 2.51);
INSERT INTO student VALUES(3887, "Avery", "Rose", "Mechanical Engineering", 3.29);
INSERT INTO student VALUES(6978, "Dante", "Soto", "Economics", 2.35);
INSERT INTO student VALUES(9354, "Tavian", "Davies", "Business Administration", 3.16);
INSERT INTO student VALUES(8397, "Meaghan", "Ford", "Mathematics", 3.89);
INSERT INTO student VALUES(4402, "Lynn", "Hubbard", "Industrial Engineering", 2.4);
INSERT INTO student VALUES(2670, "Justice", "Harris", "Electrical and Electronics Engineering", 3.86);
INSERT INTO student VALUES(2255, "Monteen", "Escobar", "Film Design", 3.04);
INSERT INTO student VALUES(245, "Syllabl", "Fitzpatric", "Animatio", 2.58);
